### ISSUE TITLE
Dont want to close the popup when the user clicks outside the popup

### ISSUE THREAD

**Issue by panbhag** [minutemailer/react-popup#20]
I don't want the popup to be closed when the user clicks outside the popup. Is this possible?

**Comment by tbleckert** [comment]
It's not really possible at the moment but is of course a good feature that would fit well in the settings. The way it works is that we have a click handler on the overlay, so you could get around this issue by disabling clicks on the overlay, or if you don't use the overlay visually you could play with the positioning/size of it.

I will get back to you later this week and we'll have this setting implemented. If you're up for it, feel free to submit a PR, always appreciated.

**Comment by BradStell** [comment]
I would like this functionality as well!

**Comment by tbleckert** [comment]
This has now been added in v0.7.1. Simply set `closeOnOutsideClick` to `false` as a property on the component. You can also use `closeOnOutsideClick` when creating a popup if you only need it on special occasions, examples in the docs.

_Please note that since version 0.7.0, the `Popup.prompt` method has been removed. It's better suitable as a plugin, see demo page for example._
