### ISSUE TITLE
Open new Popup on top of the old one

### ISSUE THREAD

**Issue by z-vr** [minutemailer/react-popup#27]
I have a form in a popup with a button, which opens another popup with a form. I'd like to complete the second form, close the second popup and come back to the first one. At the moment, it will not show the second popup before the first one is closed. Is it possible to override the queue logic?

Thanks.

**Comment by tbleckert** [comment]
At the moment this is not possible. I'm guessing you mean you want to force one popup to show directly but keep the other one still in the queue.

You could fork it and play around with the queue if you want to. I think it's a good feature but as it looks I wont have time to implement it any time soon. I'll keep the issue here until it's implemented.

If you manage to implement it, feel free to send me a PR.

**Comment by z-vr** [comment]
@tbleckert I've submitted a PR. thanks.

**Comment by tbleckert** [comment]
Published to npm and available in the 0.8.0 release. Thanks @z-vr ! I also made it available in the `alert` shortcut.
