### ISSUE TITLE
React popup not displaying

### ISSUE THREAD

**Issue by Shaikabbu** [minutemailer/react-popup#35]
Hi,
We integrate react-popup in react boilerplate project.
Added lib
Added React-popup as reference in another component.

From button click event calling popup its coming as inbuilt layer of component. 
Can you please let us know what is missing integration

Thanks

**Comment by tbleckert** [comment]
This is a global component, meaning you should not use it as a sub component. Using it as a sub component can cause visual rendering problems and other headaches. For these kinds of components it doesn't make sense sense to render it inside another component, unless that component is like a top level layout component that is always rendered.

You also need some basic CSS for the popup to display correctly, if you have not (as described in the docs), you can grab example styles from here https://github.com/minutemailer/react-popup/blob/gh-pages/popup.example.css .

Hope it helps, otherwise just get back to me and I'll reopen this issue.
